FORMAT: 1A
HOST: https://polls.apiblueprint.org/
# Tenders Page
## Tenders [/tenders]
### Current Tenders [GET]
+ Response 200 

        [
            {
                [
                    {
                        "TenderID": 1,
                        "Title": "Buy steel poles",
                        "Offer": "4000"
                        "Buyer": "BHP"
                    }, {
                        "TenderID": 2,
                        "Title": "Buy steel poles",
                        "Offer": "4500"
                        "Buyer": "BHP"
                    }, {
                        "TenderID": 3,
                        "Title": "Truck modifications",
                        "Offer": "5000"
                        "Buyer": "BMC"
                    }, {
                        "TenderID": 4,
                        "Title": "Truck modification",
                        "Offer": "4500"
                        "Buyer": "BMC"
                    }
                ]
            }
        ]